# Generated by Django 4.0.2 on 2022-02-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_question_text'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.Index(condition=models.Q(('votes__gt', 0)), fields=['votes'], name='vote_index'),
        ),
    ]
